name: Docker Compose Build Latest Main Image Tag (Manual + Nightly)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: api-build
            file: Dockerfile.multi
            image_name: solumachat-api
          - target: node
            file: Dockerfile
            image_name: solumachat

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for changes in the last 24 hours
        id: changes
        if: ${{ github.event_name == 'schedule' }}
        run: |
          COMMITS=$(git rev-list --count --since="24 hours" HEAD)
          if [ "$COMMITS" -eq 0 ]; then
            echo "skip=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Fetch tags and set the latest tag
        if: ${{ steps.changes.outputs.skip != 'true' }}
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || true)
          if [ -z "$LATEST_TAG" ]; then
            LATEST_TAG="sha-$(git rev-parse --short HEAD)"
          fi
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      # Set up QEMU
      - name: Set up QEMU
        if: ${{ steps.changes.outputs.skip != 'true' }}
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        if: ${{ steps.changes.outputs.skip != 'true' }}
        uses: docker/setup-buildx-action@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        if: ${{ steps.changes.outputs.skip != 'true' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Login to Docker Hub
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Prepare the environment
      - name: Prepare environment
        if: ${{ steps.changes.outputs.skip != 'true' }}
        run: |
          cp .env.example .env

      # Build and push Docker images for each target
      # ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:${{ env.LATEST_TAG }}
      # ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:latest
      - name: Build and push Docker images
        if: ${{ steps.changes.outputs.skip != 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.file }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:${{ env.LATEST_TAG }}
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:latest
          platforms: linux/amd64,linux/arm64
          target: ${{ matrix.target }}
